# Generated by Django 5.1.6 on 2025-03-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
