# Generated by Django 5.1.6 on 2025-03-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='B_description',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='P_description',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
